<?php
// function comment_buddy_menu() {
//     $items = array();
//     $items['add_comment'] = array(
//         'title' => 'comment!',
//         'page callback' => 'say_add_comment',
//         'access callback' => TRUE,
//         'type' => MENU_CALLBACK,
//     );
//     return $items;
// }

function comment_buddy_comment_insert(){
    drupal_set_message("Thanks for submitting a comment!");
}

function comment_buddy_comment_update(){
    drupal_set_message("Thanks for updating yr comment");
}

function comment_buddy_comment_delete(){
    drupal_set_message("Nice job deleting that");
}
