<?php
function hello_user_menu() {
    $items = array();
    $items['success'] = array(
        'title' => 'Success!',
        'page callback' => 'say_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_success() {
    return '<p>Sucessfully made a new user account!</p>';
}

function hello_user_user_insert(){
    $_GET['destination'] = 'success';
}
